package pawmatch.model;
import pawmatch.model.Enums.*;

/**
 * Created by Robert Munro on 11/12/2017.
 */
public class SimplePreferences {

  private Integer simplePreferencesId;
  private Species species;
  private Sex sex;
  private String Breed;
  private Age age;
  private Size size;
  private Boolean houseTrained;
  private CoatLength coatLength;
  private Boolean hasMedia;
  private Integer location; // zip code
  private Boolean shelteredLonger;
  private Integer userId;

  // Constructor with simplePreferencesId
  public SimplePreferences(Integer simplePreferencesId, Species species, Sex sex, String breed,
                           Age age, Size size, Boolean houseTrained, CoatLength coatLength,
                           Boolean hasMedia, Integer location, Boolean shelteredLonger, Integer
                               userId) {
    this.simplePreferencesId = simplePreferencesId;
    this.species = species;
    this.sex = sex;
    Breed = breed;
    this.age = age;
    this.size = size;
    this.houseTrained = houseTrained;
    this.coatLength = coatLength;
    this.hasMedia = hasMedia;
    this.location = location;
    this.shelteredLonger = shelteredLonger;
    this.userId = userId;
  }

  // Constructor without simplePreferencesId. Use for creating new records where the userId may not be
  // assigned yet since it is auto-generated by MySQL


  public SimplePreferences(Species species, Sex sex, String breed, Age age, Size size, Boolean
      houseTrained, CoatLength coatLength, Boolean hasMedia, Integer location, Boolean
      shelteredLonger, Integer userId) {
    this.species = species;
    this.sex = sex;
    Breed = breed;
    this.age = age;
    this.size = size;
    this.houseTrained = houseTrained;
    this.coatLength = coatLength;
    this.hasMedia = hasMedia;
    this.location = location;
    this.shelteredLonger = shelteredLonger;
    this.userId = userId;
  }

  public Integer getSimplePreferencesId() {
    return simplePreferencesId;
  }

  public void setSimplePreferencesId(Integer simplePreferencesId) {
    this.simplePreferencesId = simplePreferencesId;
  }

  public Species getSpecies() {
    return species;
  }

  public void setSpecies(Species species) {
    this.species = species;
  }

  public Sex getSex() {
    return sex;
  }

  public void setSex(Sex sex) {
    this.sex = sex;
  }

  public String getBreed() {
    return Breed;
  }

  public void setBreed(String breed) {
    Breed = breed;
  }

  public Age getAge() {
    return age;
  }

  public void setAge(Age age) {
    this.age = age;
  }

  public Size getSize() {
    return size;
  }

  public void setSize(Size size) {
    this.size = size;
  }

  public Boolean getHouseTrained() {
    return houseTrained;
  }

  public void setHouseTrained(Boolean houseTrained) {
    this.houseTrained = houseTrained;
  }

  public CoatLength getCoatLength() {
    return coatLength;
  }

  public void setCoatLength(CoatLength coatLength) {
    this.coatLength = coatLength;
  }

  public Boolean getHasMedia() {
    return hasMedia;
  }

  public void setHasMedia(Boolean hasMedia) {
    this.hasMedia = hasMedia;
  }

  public Integer getLocation() {
    return location;
  }

  public void setLocation(Integer location) {
    this.location = location;
  }

  public Boolean getShelteredLonger() {
    return shelteredLonger;
  }

  public void setShelteredLonger(Boolean shelteredLonger) {
    this.shelteredLonger = shelteredLonger;
  }

  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  @Override
  public String toString() {
    return "SimplePreferences{" +
        "simplePreferencesId=" + simplePreferencesId +
        ", species=" + species +
        ", sex=" + sex +
        ", Breed='" + Breed + '\'' +
        ", age=" + age +
        ", size=" + size +
        ", houseTrained=" + houseTrained +
        ", coatLength=" + coatLength +
        ", hasMedia=" + hasMedia +
        ", location=" + location +
        ", shelteredLonger=" + shelteredLonger +
        ", userId=" + userId +
        '}';
  }
}
